using System;
using System.Collections.Generic;

namespace BeautyBooking.Localization
{
    public static class SiteText
    {
        private static readonly IReadOnlyDictionary<string, string> Da = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            ["MetaTitle"] = "Anova Salon | Frisor i Kobenhavn",
            ["MetaDescription"] = "Anova Salon pa Amagerbrogade i Kobenhavn tilbyder professionel dameklip, herreklip og borneklip. Book tid online i dag.",
            ["NavHome"] = "Home",
            ["NavAbout"] = "Om Os",
            ["NavServices"] = "Services",
            ["NavGallery"] = "Galleri",
            ["NavContact"] = "Kontakt",
            ["NavBook"] = "Bestil Online",
            ["HeroBrand"] = "SALON ANOVA",
            ["HeroTitle"] = "Eksklusiv haircare med fokus pa detaljer",
            ["HeroLead"] = "Step ind i et roligt rum for moderne klip, styling og personlig service. Vi kombinerer klassisk handvaerk med nutidigt look i hjertet af Amager.",
            ["HeroBook"] = "Bestil tid",
            ["HeroViewServices"] = "Se services",
            ["AboutEyebrow"] = "About us",
            ["AboutTitle"] = "Passion for detail i hver behandling",
            ["AboutText1"] = "Velkommen til Anova, Salon din nye hardestination i Kobenhavn. Uanset om du er mand, kvinde, barn eller senior, tilpasser vi hver behandling til dit behov og din stil.",
            ["AboutText2"] = "Vores erfarne stylister arbejder med produkter af hoj kvalitet i afslappede omgivelser, sa du gar herfra med et look der holder.",
            ["AboutBook"] = "Book appointment",
            ["ServicesEyebrow"] = "Our services",
            ["ServicesTitle"] = "Populaere behandlinger",
            ["Service1Name"] = "Herreklip",
            ["Service1Text"] = "Klassisk eller moderne herreklip med professionel finish.",
            ["Service1Meta"] = "30 min",
            ["Service1Price"] = "369 DKK",
            ["Service2Name"] = "Dameklip",
            ["Service2Text"] = "Skraddersyet dameklip med fokus pa form, volumen og stil.",
            ["Service2Meta"] = "45 min",
            ["Service2Price"] = "fra 459 DKK",
            ["Service3Name"] = "Born under 12",
            ["Service3Text"] = "Tryg og rolig klipning med tid til de mindste kunder.",
            ["Service3Meta"] = "25 min",
            ["Service3Price"] = "239 DKK",
            ["Service4Name"] = "Styling",
            ["Service4Text"] = "Styling til event, hverdag eller et hurtigt polish af dit look.",
            ["Service4Meta"] = "30 min",
            ["Service4Price"] = "fra 299 DKK",
            ["BookOnline"] = "Bestil Online",
            ["GalleryEyebrow"] = "Gallery",
            ["GalleryTitle"] = "Udvalgte resultater",
            ["HoursEyebrow"] = "Opening hours",
            ["HoursTitle"] = "Vi har abent naesten hele ugen",
            ["Mon"] = "Mandag",
            ["Tue"] = "Tirsdag",
            ["Wed"] = "Onsdag",
            ["Thu"] = "Torsdag",
            ["Fri"] = "Fredag",
            ["Sat"] = "Lordag",
            ["Sun"] = "Sondag",
            ["Closed"] = "Lukket",
            ["ContactEyebrow"] = "Contact",
            ["ContactName"] = "Salon Anova",
            ["ContactAddress"] = "Amagerbrogade 219, 2300 Kobenhavn S",
            ["Instagram"] = "Instagram",
            ["FindWay"] = "Find vej",
            ["BookingTitle"] = "Klar til et nyt look?",
            ["BookingText"] = "Book din tid online pa under et minut.",
            ["BookingCta"] = "Bestil Online",
            ["FooterTagline"] = "Eksklusiv craftsmanship og wellness i hjertet af Amager.",
            ["FooterQuickLinks"] = "Quick links",
            ["FooterBook"] = "Book",
            ["FooterBookText"] = "Book direkte pa vores interne bookingside.",
            ["FooterGoBooking"] = "Ga til booking",
            ["FooterCopyright"] = "© 2026 Anova Salon. All rights reserved."
        };

        private static readonly IReadOnlyDictionary<string, string> En = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            ["MetaTitle"] = "Anova Salon | Hairdresser in Copenhagen",
            ["MetaDescription"] = "Anova Salon in Copenhagen offers professional haircuts for women, men, and children. Book your appointment online today.",
            ["NavHome"] = "Home",
            ["NavAbout"] = "About",
            ["NavServices"] = "Services",
            ["NavGallery"] = "Gallery",
            ["NavContact"] = "Contact",
            ["NavBook"] = "Book Online",
            ["HeroBrand"] = "SALON ANOVA",
            ["HeroTitle"] = "Exclusive haircare with attention to detail",
            ["HeroLead"] = "Step into a calm space for modern cuts, styling, and personal service. We combine classic craft with a modern look in the heart of Amager.",
            ["HeroBook"] = "Book now",
            ["HeroViewServices"] = "View services",
            ["AboutEyebrow"] = "About us",
            ["AboutTitle"] = "Passion for detail in every treatment",
            ["AboutText1"] = "Welcome to Anova Salon, your new hair destination in Copenhagen. Whether you are a man, woman, child, or senior, we tailor each treatment to your style and needs.",
            ["AboutText2"] = "Our experienced stylists use high quality products in a relaxed atmosphere, so you leave with a look that lasts.",
            ["AboutBook"] = "Book appointment",
            ["ServicesEyebrow"] = "Our services",
            ["ServicesTitle"] = "Popular treatments",
            ["Service1Name"] = "Men's haircut",
            ["Service1Text"] = "Classic or modern men's haircut with a professional finish.",
            ["Service1Meta"] = "30 min",
            ["Service1Price"] = "369 DKK",
            ["Service2Name"] = "Women's haircut",
            ["Service2Text"] = "Tailored women's haircut focused on shape, volume, and style.",
            ["Service2Meta"] = "45 min",
            ["Service2Price"] = "from 459 DKK",
            ["Service3Name"] = "Children under 12",
            ["Service3Text"] = "Calm and comfortable haircut for younger guests.",
            ["Service3Meta"] = "25 min",
            ["Service3Price"] = "239 DKK",
            ["Service4Name"] = "Styling",
            ["Service4Text"] = "Styling for events, everyday polish, or a fast refresh.",
            ["Service4Meta"] = "30 min",
            ["Service4Price"] = "from 299 DKK",
            ["BookOnline"] = "Book Online",
            ["GalleryEyebrow"] = "Gallery",
            ["GalleryTitle"] = "Selected results",
            ["HoursEyebrow"] = "Opening hours",
            ["HoursTitle"] = "Open almost every day",
            ["Mon"] = "Monday",
            ["Tue"] = "Tuesday",
            ["Wed"] = "Wednesday",
            ["Thu"] = "Thursday",
            ["Fri"] = "Friday",
            ["Sat"] = "Saturday",
            ["Sun"] = "Sunday",
            ["Closed"] = "Closed",
            ["ContactEyebrow"] = "Contact",
            ["ContactName"] = "Salon Anova",
            ["ContactAddress"] = "Amagerbrogade 219, 2300 Copenhagen S",
            ["Instagram"] = "Instagram",
            ["FindWay"] = "Get directions",
            ["BookingTitle"] = "Ready for a new look?",
            ["BookingText"] = "Book your appointment online in under a minute.",
            ["BookingCta"] = "Book Online",
            ["FooterTagline"] = "Exclusive craftsmanship and wellness in the heart of Amager.",
            ["FooterQuickLinks"] = "Quick links",
            ["FooterBook"] = "Book",
            ["FooterBookText"] = "Book directly on our internal booking page.",
            ["FooterGoBooking"] = "Go to booking",
            ["FooterCopyright"] = "© 2026 Anova Salon. All rights reserved."
        };

        private static readonly IReadOnlyDictionary<string, string> Fr = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            ["MetaTitle"] = "Anova Salon | Coiffeur a Copenhague",
            ["MetaDescription"] = "Anova Salon a Copenhague propose des coupes professionnelles pour femmes, hommes et enfants. Reservez en ligne des aujourd'hui.",
            ["NavHome"] = "Accueil",
            ["NavAbout"] = "A propos",
            ["NavServices"] = "Services",
            ["NavGallery"] = "Galerie",
            ["NavContact"] = "Contact",
            ["NavBook"] = "Reserver",
            ["HeroBrand"] = "SALON ANOVA",
            ["HeroTitle"] = "Soins capillaires exclusifs avec precision",
            ["HeroLead"] = "Entrez dans un espace calme pour des coupes modernes, du styling et un service personnalise. Nous combinons savoir-faire classique et style moderne au coeur d'Amager.",
            ["HeroBook"] = "Reserver",
            ["HeroViewServices"] = "Voir services",
            ["AboutEyebrow"] = "A propos",
            ["AboutTitle"] = "Passion du detail a chaque soin",
            ["AboutText1"] = "Bienvenue chez Anova Salon, votre nouvelle destination cheveux a Copenhague. Nous adaptons chaque soin a vos besoins et a votre style.",
            ["AboutText2"] = "Nos stylistes experimentes utilisent des produits de haute qualite dans une atmosphere detendue pour un resultat durable.",
            ["AboutBook"] = "Reserver",
            ["ServicesEyebrow"] = "Nos services",
            ["ServicesTitle"] = "Soins populaires",
            ["Service1Name"] = "Coupe homme",
            ["Service1Text"] = "Coupe homme classique ou moderne avec finition professionnelle.",
            ["Service1Meta"] = "30 min",
            ["Service1Price"] = "369 DKK",
            ["Service2Name"] = "Coupe femme",
            ["Service2Text"] = "Coupe femme sur mesure avec focus sur forme, volume et style.",
            ["Service2Meta"] = "45 min",
            ["Service2Price"] = "a partir de 459 DKK",
            ["Service3Name"] = "Enfants moins de 12 ans",
            ["Service3Text"] = "Coupe calme et confortable pour les enfants.",
            ["Service3Meta"] = "25 min",
            ["Service3Price"] = "239 DKK",
            ["Service4Name"] = "Styling",
            ["Service4Text"] = "Styling pour evenement, quotidien ou retouche rapide.",
            ["Service4Meta"] = "30 min",
            ["Service4Price"] = "a partir de 299 DKK",
            ["BookOnline"] = "Reserver",
            ["GalleryEyebrow"] = "Galerie",
            ["GalleryTitle"] = "Resultats selectionnes",
            ["HoursEyebrow"] = "Horaires",
            ["HoursTitle"] = "Ouvert presque tous les jours",
            ["Mon"] = "Lundi",
            ["Tue"] = "Mardi",
            ["Wed"] = "Mercredi",
            ["Thu"] = "Jeudi",
            ["Fri"] = "Vendredi",
            ["Sat"] = "Samedi",
            ["Sun"] = "Dimanche",
            ["Closed"] = "Ferme",
            ["ContactEyebrow"] = "Contact",
            ["ContactName"] = "Salon Anova",
            ["ContactAddress"] = "Amagerbrogade 219, 2300 Copenhague S",
            ["Instagram"] = "Instagram",
            ["FindWay"] = "Itineraire",
            ["BookingTitle"] = "Pret pour un nouveau look ?",
            ["BookingText"] = "Reservez votre rendez-vous en ligne en moins d'une minute.",
            ["BookingCta"] = "Reserver",
            ["FooterTagline"] = "Savoir-faire exclusif et bien-etre au coeur d'Amager.",
            ["FooterQuickLinks"] = "Liens rapides",
            ["FooterBook"] = "Reservation",
            ["FooterBookText"] = "Reservez directement via notre page interne.",
            ["FooterGoBooking"] = "Aller a reservation",
            ["FooterCopyright"] = "© 2026 Anova Salon. Tous droits reserves."
        };

        private static readonly IReadOnlyDictionary<string, string> De = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            ["MetaTitle"] = "Anova Salon | Friseur in Kopenhagen",
            ["MetaDescription"] = "Anova Salon in Kopenhagen bietet professionelle Haarschnitte fur Damen, Herren und Kinder. Buchen Sie noch heute online.",
            ["NavHome"] = "Start",
            ["NavAbout"] = "Uber uns",
            ["NavServices"] = "Leistungen",
            ["NavGallery"] = "Galerie",
            ["NavContact"] = "Kontakt",
            ["NavBook"] = "Online buchen",
            ["HeroBrand"] = "SALON ANOVA",
            ["HeroTitle"] = "Exklusive Haarpflege mit Liebe zum Detail",
            ["HeroLead"] = "Willkommen in einem ruhigen Raum fur moderne Schnitte, Styling und personlichen Service. Wir verbinden klassisches Handwerk mit modernem Look im Herzen von Amager.",
            ["HeroBook"] = "Jetzt buchen",
            ["HeroViewServices"] = "Leistungen ansehen",
            ["AboutEyebrow"] = "Uber uns",
            ["AboutTitle"] = "Leidenschaft fur Details bei jeder Behandlung",
            ["AboutText1"] = "Willkommen bei Anova Salon, Ihrem neuen Haarziel in Kopenhagen. Wir passen jede Behandlung an Ihren Stil und Ihre Bedurfnisse an.",
            ["AboutText2"] = "Unsere erfahrenen Stylisten arbeiten mit hochwertigen Produkten in entspannter Atmosphare fur ein Ergebnis, das bleibt.",
            ["AboutBook"] = "Termin buchen",
            ["ServicesEyebrow"] = "Unsere Leistungen",
            ["ServicesTitle"] = "Beliebte Behandlungen",
            ["Service1Name"] = "Herrenhaarschnitt",
            ["Service1Text"] = "Klassischer oder moderner Herrenhaarschnitt mit professionellem Finish.",
            ["Service1Meta"] = "30 Min",
            ["Service1Price"] = "369 DKK",
            ["Service2Name"] = "Damenhaarschnitt",
            ["Service2Text"] = "Massgeschneiderter Damenhaarschnitt mit Fokus auf Form, Volumen und Stil.",
            ["Service2Meta"] = "45 Min",
            ["Service2Price"] = "ab 459 DKK",
            ["Service3Name"] = "Kinder unter 12",
            ["Service3Text"] = "Ruhiger und angenehmer Haarschnitt fur Kinder.",
            ["Service3Meta"] = "25 Min",
            ["Service3Price"] = "239 DKK",
            ["Service4Name"] = "Styling",
            ["Service4Text"] = "Styling fur Events, Alltag oder schnelles Auffrischen.",
            ["Service4Meta"] = "30 Min",
            ["Service4Price"] = "ab 299 DKK",
            ["BookOnline"] = "Online buchen",
            ["GalleryEyebrow"] = "Galerie",
            ["GalleryTitle"] = "Ausgewahlte Ergebnisse",
            ["HoursEyebrow"] = "Offnungszeiten",
            ["HoursTitle"] = "Fast jeden Tag geoffnet",
            ["Mon"] = "Montag",
            ["Tue"] = "Dienstag",
            ["Wed"] = "Mittwoch",
            ["Thu"] = "Donnerstag",
            ["Fri"] = "Freitag",
            ["Sat"] = "Samstag",
            ["Sun"] = "Sonntag",
            ["Closed"] = "Geschlossen",
            ["ContactEyebrow"] = "Kontakt",
            ["ContactName"] = "Salon Anova",
            ["ContactAddress"] = "Amagerbrogade 219, 2300 Kopenhagen S",
            ["Instagram"] = "Instagram",
            ["FindWay"] = "Route",
            ["BookingTitle"] = "Bereit fur einen neuen Look?",
            ["BookingText"] = "Buchen Sie Ihren Termin online in unter einer Minute.",
            ["BookingCta"] = "Online buchen",
            ["FooterTagline"] = "Exklusive Handwerkskunst und Wellness im Herzen von Amager.",
            ["FooterQuickLinks"] = "Schnellzugriffe",
            ["FooterBook"] = "Buchung",
            ["FooterBookText"] = "Buchen Sie direkt uber unsere interne Buchungsseite.",
            ["FooterGoBooking"] = "Zur Buchung",
            ["FooterCopyright"] = "© 2026 Anova Salon. Alle Rechte vorbehalten."
        };

        public static string Get(string key, string language)
        {
            var lang = (language ?? "da").ToLowerInvariant();
            var selected = lang switch
            {
                "en" => En,
                "fr" => Fr,
                "de" => De,
                _ => Da
            };

            if (selected.TryGetValue(key, out var value))
            {
                return value;
            }

            if (Da.TryGetValue(key, out var fallback))
            {
                return fallback;
            }

            return key;
        }
    }
}
