from typing import Dict

DA: Dict[str, str] = {
    "MetaTitle": "Anova Salon | Frisor i Kobenhavn",
    "MetaDescription": "Anova Salon pa Amagerbrogade i Kobenhavn tilbyder professionel dameklip, herreklip og borneklip. Book tid online i dag.",
    "NavHome": "Home",
    "NavAbout": "Om Os",
    "NavServices": "Services",
    "NavGallery": "Galleri",
    "NavHours": "Abningstider",
    "NavContact": "Kontakt",
    "NavBook": "Bestil Online",
    "HeroBrand": "SALON ANOVA",
    "HeroTitle": "Eksklusiv haircare med fokus pa detaljer",
    "HeroLead": "Step ind i et roligt rum for moderne klip, styling og personlig service. Vi kombinerer klassisk handvaerk med nutidigt look i hjertet af Amager.",
    "HeroBook": "Bestil tid",
    "HeroViewServices": "Se services",
    "AboutEyebrow": "About us",
    "AboutTitle": "Passion for detail i hver behandling",
    "AboutText1": "Velkommen til Anova Salon, din nye hardestination i Kobenhavn. Uanset om du er mand, kvinde, barn eller senior, tilpasser vi hver behandling til dit behov og din stil.",
    "AboutText2": "Vores erfarne stylister arbejder med produkter af hoj kvalitet i afslappede omgivelser, sa du gar herfra med et look der holder.",
    "AboutBook": "Book appointment",
    "ServicesEyebrow": "Our services",
    "ServicesTitle": "Populaere behandlinger",
    "Service1Name": "Herreklip",
    "Service1Text": "Klassisk eller moderne herreklip med professionel finish.",
    "Service1Meta": "15 min",
    "Service1Price": "160 DKK",
    "Service2Name": "Dameklip",
    "Service2Text": "Skraeddersyet dameklip med fokus pa form, volumen og stil.",
    "Service2Meta": "30 min",
    "Service2Price": "300 DKK",
    "Service3Name": "Born under 8",
    "Service3Text": "Tryg og rolig klipning med tid til de mindste kunder.",
    "Service3Meta": "15 min",
    "Service3Price": "140 DKK",
    "Service4Name": "Styling",
    "Service4Text": "Styling til event, hverdag eller et hurtigt polish af dit look.",
    "Service4Meta": "30 min",
    "Service4Price": "fra 300 DKK",
    "Service5Name": "Skaeg",
    "Service5Text": "Skaegtrimning og formgivning med praecision.",
    "Service5Meta": "15 min",
    "Service5Price": "100 DKK",
    "Service6Name": "Skin fade",
    "Service6Text": "Skarp skin fade med praecis overgang fra hud til har.",
    "Service6Meta": "15 min",
    "Service6Price": "180 DKK",
    "Service7Name": "Herre klip med saks",
    "Service7Text": "Klassisk herreklip udelukkende med saks for et blodt og naturligt resultat.",
    "Service7Meta": "15 min",
    "Service7Price": "180 DKK",
    "BookOnline": "Bestil Online",
    "GalleryEyebrow": "Gallery",
    "GalleryTitle": "Udvalgte resultater",
    "HoursEyebrow": "Abningstider",
    "HoursTitle": "Vi har abent naesten hele ugen",
    "Mon": "Mandag",
    "Tue": "Tirsdag",
    "Wed": "Onsdag",
    "Thu": "Torsdag",
    "Fri": "Fredag",
    "Sat": "Lordag",
    "Sun": "Sondag",
    "Closed": "Lukket",
    "ContactEyebrow": "Kontakt",
    "ContactName": "Salon Anova",
    "ContactAddress": "Amagerbrogade 219, 2300 Kobenhavn S",
    "Instagram": "Instagram",
    "FindWay": "Find vej",
    "BookingTitle": "Klar til et nyt look?",
    "BookingText": "Book din tid online pa under et minut.",
    "BookingCta": "Bestil Online",
    "FooterTagline": "Eksklusiv craftsmanship og wellness i hjertet af Amager.",
    "FooterQuickLinks": "Quick links",
    "FooterBook": "Book",
    "FooterBookText": "Book direkte pa vores interne bookingside.",
    "FooterGoBooking": "Ga til booking",
    "FooterCopyright": "(c) 2026 Anova Salon. All rights reserved.",
}

EN: Dict[str, str] = {
    "MetaTitle": "Anova Salon | Hairdresser in Copenhagen",
    "MetaDescription": "Anova Salon in Copenhagen offers professional haircuts for women, men, and children. Book your appointment online today.",
    "NavHome": "Home",
    "NavAbout": "About",
    "NavServices": "Services",
    "NavGallery": "Gallery",
    "NavHours": "Hours",
    "NavContact": "Contact",
    "NavBook": "Book Online",
    "HeroBrand": "SALON ANOVA",
    "HeroTitle": "Exclusive haircare with attention to detail",
    "HeroLead": "Step into a calm space for modern cuts, styling, and personal service. We combine classic craft with a modern look in the heart of Amager.",
    "HeroBook": "Book now",
    "HeroViewServices": "View services",
    "AboutEyebrow": "About us",
    "AboutTitle": "Passion for detail in every treatment",
    "AboutText1": "Welcome to Anova Salon, your new hair destination in Copenhagen. Whether you are a man, woman, child, or senior, we tailor each treatment to your style and needs.",
    "AboutText2": "Our experienced stylists use high quality products in a relaxed atmosphere, so you leave with a look that lasts.",
    "AboutBook": "Book appointment",
    "ServicesEyebrow": "Our services",
    "ServicesTitle": "Popular treatments",
    "Service1Name": "Men's haircut",
    "Service1Text": "Classic or modern men's haircut with a professional finish.",
    "Service1Meta": "15 min",
    "Service1Price": "160 DKK",
    "Service2Name": "Women's haircut",
    "Service2Text": "Tailored women's haircut focused on shape, volume, and style.",
    "Service2Meta": "30 min",
    "Service2Price": "300 DKK",
    "Service3Name": "Children under 8",
    "Service3Text": "Calm and comfortable haircut for younger guests.",
    "Service3Meta": "15 min",
    "Service3Price": "140 DKK",
    "Service4Name": "Styling",
    "Service4Text": "Styling for events, everyday polish, or a fast refresh.",
    "Service4Meta": "30 min",
    "Service4Price": "from 300 DKK",
    "Service5Name": "Beard",
    "Service5Text": "Beard trim and shaping with precision.",
    "Service5Meta": "15 min",
    "Service5Price": "100 DKK",
    "Service6Name": "Skin fade",
    "Service6Text": "Sharp skin fade with a precise blend from skin to hair.",
    "Service6Meta": "15 min",
    "Service6Price": "180 DKK",
    "Service7Name": "Men's haircut with scissors",
    "Service7Text": "Classic men's haircut using scissors only for a soft, natural finish.",
    "Service7Meta": "15 min",
    "Service7Price": "180 DKK",
    "BookOnline": "Book Online",
    "GalleryEyebrow": "Gallery",
    "GalleryTitle": "Selected results",
    "HoursEyebrow": "Opening hours",
    "HoursTitle": "Open almost every day",
    "Mon": "Monday",
    "Tue": "Tuesday",
    "Wed": "Wednesday",
    "Thu": "Thursday",
    "Fri": "Friday",
    "Sat": "Saturday",
    "Sun": "Sunday",
    "Closed": "Closed",
    "ContactEyebrow": "Contact",
    "ContactName": "Salon Anova",
    "ContactAddress": "Amagerbrogade 219, 2300 Copenhagen S",
    "Instagram": "Instagram",
    "FindWay": "Get directions",
    "BookingTitle": "Ready for a new look?",
    "BookingText": "Book your appointment online in under a minute.",
    "BookingCta": "Book Online",
    "FooterTagline": "Exclusive craftsmanship and wellness in the heart of Amager.",
    "FooterQuickLinks": "Quick links",
    "FooterBook": "Book",
    "FooterBookText": "Book directly on our internal booking page.",
    "FooterGoBooking": "Go to booking",
    "FooterCopyright": "(c) 2026 Anova Salon. All rights reserved.",
}

FR: Dict[str, str] = {
    "MetaTitle": "Anova Salon | Coiffeur a Copenhague",
    "MetaDescription": "Anova Salon a Copenhague propose des coupes professionnelles pour femmes, hommes et enfants. Reservez en ligne des aujourd'hui.",
    "NavHome": "Accueil",
    "NavAbout": "A propos",
    "NavServices": "Services",
    "NavGallery": "Galerie",
    "NavHours": "Horaires",
    "NavContact": "Contact",
    "NavBook": "Reserver",
    "HeroBrand": "SALON ANOVA",
    "HeroTitle": "Soins capillaires exclusifs avec precision",
    "HeroLead": "Entrez dans un espace calme pour des coupes modernes, du styling et un service personnalise. Nous combinons savoir-faire classique et style moderne au coeur d'Amager.",
    "HeroBook": "Reserver",
    "HeroViewServices": "Voir services",
    "AboutEyebrow": "A propos",
    "AboutTitle": "Passion du detail a chaque soin",
    "AboutText1": "Bienvenue chez Anova Salon, votre nouvelle destination cheveux a Copenhague. Nous adaptons chaque soin a vos besoins et a votre style.",
    "AboutText2": "Nos stylistes experimentes utilisent des produits de haute qualite dans une atmosphere detendue pour un resultat durable.",
    "AboutBook": "Reserver",
    "ServicesEyebrow": "Nos services",
    "ServicesTitle": "Soins populaires",
    "Service1Name": "Coupe homme",
    "Service1Text": "Coupe homme classique ou moderne avec finition professionnelle.",
    "Service1Meta": "15 min",
    "Service1Price": "160 DKK",
    "Service2Name": "Coupe femme",
    "Service2Text": "Coupe femme sur mesure avec focus sur forme, volume et style.",
    "Service2Meta": "30 min",
    "Service2Price": "300 DKK",
    "Service3Name": "Enfants moins de 8 ans",
    "Service3Text": "Coupe calme et confortable pour les enfants.",
    "Service3Meta": "15 min",
    "Service3Price": "140 DKK",
    "Service4Name": "Styling",
    "Service4Text": "Styling pour evenement, quotidien ou retouche rapide.",
    "Service4Meta": "30 min",
    "Service4Price": "a partir de 300 DKK",
    "Service5Name": "Barbe",
    "Service5Text": "Taille et mise en forme de la barbe avec precision.",
    "Service5Meta": "15 min",
    "Service5Price": "100 DKK",
    "Service6Name": "Skin fade",
    "Service6Text": "Skin fade net avec une transition precise de la peau aux cheveux.",
    "Service6Meta": "15 min",
    "Service6Price": "180 DKK",
    "Service7Name": "Coupe homme aux ciseaux",
    "Service7Text": "Coupe homme classique aux ciseaux uniquement pour un resultat naturel.",
    "Service7Meta": "15 min",
    "Service7Price": "180 DKK",
    "BookOnline": "Reserver",
    "GalleryEyebrow": "Galerie",
    "GalleryTitle": "Resultats selectionnes",
    "HoursEyebrow": "Horaires",
    "HoursTitle": "Ouvert presque tous les jours",
    "Mon": "Lundi",
    "Tue": "Mardi",
    "Wed": "Mercredi",
    "Thu": "Jeudi",
    "Fri": "Vendredi",
    "Sat": "Samedi",
    "Sun": "Dimanche",
    "Closed": "Ferme",
    "ContactEyebrow": "Contact",
    "ContactName": "Salon Anova",
    "ContactAddress": "Amagerbrogade 219, 2300 Copenhague S",
    "Instagram": "Instagram",
    "FindWay": "Itineraire",
    "BookingTitle": "Pret pour un nouveau look ?",
    "BookingText": "Reservez votre rendez-vous en ligne en moins d'une minute.",
    "BookingCta": "Reserver",
    "FooterTagline": "Savoir-faire exclusif et bien-etre au coeur d'Amager.",
    "FooterQuickLinks": "Liens rapides",
    "FooterBook": "Reservation",
    "FooterBookText": "Reservez directement via notre page interne.",
    "FooterGoBooking": "Aller a la reservation",
    "FooterCopyright": "(c) 2026 Anova Salon. Tous droits reserves.",
}

DE: Dict[str, str] = {
    "MetaTitle": "Anova Salon | Friseur in Kopenhagen",
    "MetaDescription": "Anova Salon in Kopenhagen bietet professionelle Haarschnitte fur Damen, Herren und Kinder. Buchen Sie noch heute online.",
    "NavHome": "Start",
    "NavAbout": "Uber uns",
    "NavServices": "Leistungen",
    "NavGallery": "Galerie",
    "NavHours": "Offnungszeiten",
    "NavContact": "Kontakt",
    "NavBook": "Online buchen",
    "HeroBrand": "SALON ANOVA",
    "HeroTitle": "Exklusive Haarpflege mit Liebe zum Detail",
    "HeroLead": "Willkommen in einem ruhigen Raum fur moderne Schnitte, Styling und personlichen Service. Wir verbinden klassisches Handwerk mit modernem Look im Herzen von Amager.",
    "HeroBook": "Jetzt buchen",
    "HeroViewServices": "Leistungen ansehen",
    "AboutEyebrow": "Uber uns",
    "AboutTitle": "Leidenschaft fur Details bei jeder Behandlung",
    "AboutText1": "Willkommen bei Anova Salon, Ihrem neuen Haarziel in Kopenhagen. Wir passen jede Behandlung an Ihren Stil und Ihre Bedurfnisse an.",
    "AboutText2": "Unsere erfahrenen Stylisten arbeiten mit hochwertigen Produkten in entspannter Atmosphare fur ein Ergebnis, das bleibt.",
    "AboutBook": "Termin buchen",
    "ServicesEyebrow": "Unsere Leistungen",
    "ServicesTitle": "Beliebte Behandlungen",
    "Service1Name": "Herrenhaarschnitt",
    "Service1Text": "Klassischer oder moderner Herrenhaarschnitt mit professionellem Finish.",
    "Service1Meta": "15 Min",
    "Service1Price": "160 DKK",
    "Service2Name": "Damenhaarschnitt",
    "Service2Text": "Massgeschneiderter Damenhaarschnitt mit Fokus auf Form, Volumen und Stil.",
    "Service2Meta": "30 Min",
    "Service2Price": "300 DKK",
    "Service3Name": "Kinder unter 8",
    "Service3Text": "Ruhiger und angenehmer Haarschnitt fur Kinder.",
    "Service3Meta": "15 Min",
    "Service3Price": "140 DKK",
    "Service4Name": "Styling",
    "Service4Text": "Styling fur Events, Alltag oder schnelles Auffrischen.",
    "Service4Meta": "30 Min",
    "Service4Price": "ab 300 DKK",
    "Service5Name": "Bart",
    "Service5Text": "Bartpflege und Formgebung mit Prazision.",
    "Service5Meta": "15 Min",
    "Service5Price": "100 DKK",
    "Service6Name": "Skin fade",
    "Service6Text": "Praziser Skin Fade mit sauberem Ubergang von Haut zu Haar.",
    "Service6Meta": "15 Min",
    "Service6Price": "180 DKK",
    "Service7Name": "Herrenhaarschnitt mit Schere",
    "Service7Text": "Klassischer Herrenhaarschnitt nur mit der Schere fur ein naturliches Ergebnis.",
    "Service7Meta": "15 Min",
    "Service7Price": "180 DKK",
    "BookOnline": "Online buchen",
    "GalleryEyebrow": "Galerie",
    "GalleryTitle": "Ausgewahlte Ergebnisse",
    "HoursEyebrow": "Offnungszeiten",
    "HoursTitle": "Fast jeden Tag geoffnet",
    "Mon": "Montag",
    "Tue": "Dienstag",
    "Wed": "Mittwoch",
    "Thu": "Donnerstag",
    "Fri": "Freitag",
    "Sat": "Samstag",
    "Sun": "Sonntag",
    "Closed": "Geschlossen",
    "ContactEyebrow": "Kontakt",
    "ContactName": "Salon Anova",
    "ContactAddress": "Amagerbrogade 219, 2300 Kopenhagen S",
    "Instagram": "Instagram",
    "FindWay": "Route",
    "BookingTitle": "Bereit fur einen neuen Look?",
    "BookingText": "Buchen Sie Ihren Termin online in unter einer Minute.",
    "BookingCta": "Online buchen",
    "FooterTagline": "Exklusive Handwerkskunst und Wellness im Herzen von Amager.",
    "FooterQuickLinks": "Schnellzugriffe",
    "FooterBook": "Buchung",
    "FooterBookText": "Buchen Sie direkt uber unsere interne Buchungsseite.",
    "FooterGoBooking": "Zur Buchung",
    "FooterCopyright": "(c) 2026 Anova Salon. Alle Rechte vorbehalten.",
}

ZH: Dict[str, str] = {
    "MetaTitle": "Anova Salon | Ge Ben Ha Gen Mei Fa Sha Long",
    "MetaDescription": "Anova Salon zai Ge Ben Ha Gen ti gong zhuan ye nan nu ji er tong li fa fu wu. Li ji zai xian yu yue.",
    "NavHome": "Shou Ye",
    "NavAbout": "Guan Yu Wo Men",
    "NavServices": "Fu Wu",
    "NavGallery": "Zuo Pin Ji",
    "NavHours": "Ying Ye Shi Jian",
    "NavContact": "Lian Xi",
    "NavBook": "Zai Xian Yu Yue",
    "HeroBrand": "SALON ANOVA",
    "HeroTitle": "Zhu Zhong Xi Jie De Gao Duan Hu Fa Ti Yan",
    "HeroLead": "Zai zhe li xiang shou xian dai jian fa, zao xing he tie xin fu wu.",
    "HeroBook": "Li Ji Yu Yue",
    "HeroViewServices": "Cha Kan Fu Wu",
    "AboutEyebrow": "Guan Yu Wo Men",
    "AboutTitle": "Mei Yi Ci Fu Wu Dou Zhuan Zhu Xi Jie",
    "AboutText1": "Huan ying lai dao Anova Salon.",
    "AboutText2": "Wo men jing yan feng fu de zao xing shi rang nin yong you chi jiu jing zhi de zao xing.",
    "AboutBook": "Yu Yue Fu Wu",
    "ServicesEyebrow": "Wo Men De Fu Wu",
    "ServicesTitle": "Re Men Xiang Mu",
    "Service1Name": "Nan Shi Li Fa",
    "Service1Text": "Jing Dian huo xian dai nan shi li fa.",
    "Service1Meta": "15 Fen Zhong",
    "Service1Price": "160 DKK",
    "Service2Name": "Nu Shi Li Fa",
    "Service2Text": "Gen ju lian xing yu feng ge ding zhi.",
    "Service2Meta": "30 Fen Zhong",
    "Service2Price": "300 DKK",
    "Service3Name": "8 Sui Yi Xia Er Tong",
    "Service3Text": "Wei xiao peng you ti gong shu shi ti yan.",
    "Service3Meta": "15 Fen Zhong",
    "Service3Price": "140 DKK",
    "Service4Name": "Zao Xing",
    "Service4Text": "Shi yong yu huo dong huo ri chang.",
    "Service4Meta": "30 Fen Zhong",
    "Service4Price": "300 DKK Qi",
    "Service5Name": "Hu Xu Xiu Jian",
    "Service5Text": "Jing zhun xiu jian yu su xing.",
    "Service5Meta": "15 Fen Zhong",
    "Service5Price": "100 DKK",
    "Service6Name": "Jian Bian Duan Fa",
    "Service6Text": "Jing zhun jian bian guo du zi ran.",
    "Service6Meta": "15 Fen Zhong",
    "Service6Price": "180 DKK",
    "Service7Name": "Nan Shi Jian Dao Li Fa",
    "Service7Text": "Chun jian dao nan shi li fa.",
    "Service7Meta": "15 Fen Zhong",
    "Service7Price": "180 DKK",
    "BookOnline": "Zai Xian Yu Yue",
    "GalleryEyebrow": "Zuo Pin Ji",
    "GalleryTitle": "Jing Xuan Cheng Guo",
    "HoursEyebrow": "Ying Ye Shi Jian",
    "HoursTitle": "Ji Hu Mei Tian Ying Ye",
    "Mon": "Zhou Yi",
    "Tue": "Zhou Er",
    "Wed": "Zhou San",
    "Thu": "Zhou Si",
    "Fri": "Zhou Wu",
    "Sat": "Zhou Liu",
    "Sun": "Zhou Ri",
    "Closed": "Xiu Xi",
    "ContactEyebrow": "Lian Xi",
    "ContactName": "Salon Anova",
    "ContactAddress": "Amagerbrogade 219, 2300 Copenhagen S",
    "Instagram": "Instagram",
    "FindWay": "Di Tu Dao Hang",
    "BookingTitle": "Zhun Bei Huan Ge Xin Zao Xing Ma?",
    "BookingText": "Bu dao yi fen zhong ji ke wan cheng zai xian yu yue.",
    "BookingCta": "Zai Xian Yu Yue",
    "FooterTagline": "Ti yan gao duan jiang xin yu shu shi hu li.",
    "FooterQuickLinks": "Kuai Jie Lian Jie",
    "FooterBook": "Yu Yue",
    "FooterBookText": "Tong guo wo men de nei bu yu yue ye mian zhi jie xia dan.",
    "FooterGoBooking": "Qian Wang Yu Yue",
    "FooterCopyright": "(c) 2026 Anova Salon. Bao Liu Suo You Quan Li.",
}

LANG_MAP = {
    "da": DA,
    "en": EN,
    "fr": FR,
    "de": DE,
    "zh": ZH,
}


def get_text(language: str, key: str) -> str:
    selected = LANG_MAP.get((language or "da").lower(), DA)
    if key in selected:
        return selected[key]
    if key in DA:
        return DA[key]
    return key
